repository:
  name: mvp-frontend
  description: "React 19 MVP frontend application"
  private: true
  has_issues: true
  has_projects: true
  has_wiki: false
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
  delete_branch_on_merge: false

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "test-and-build"
      enforce_admins: false
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
        dismissal_restrictions:
          users: []
          teams: []
      restrictions: null
      allow_force_pushes: false
      allow_deletions: false
